simple:
  namespace: hail_data

  drivers:
    yac:
      ttl: 86400
    redis:
      ttl: 604800

pool:
  driver: simple # hierarchical, namespaced

  config: [] # for init simple cache
  namespace: "" # for NamespacedCachePool