parameters:
  # ...

services:
  # Feature
  config: Hail\Config
  alias:
      class: Hail\AliasLoader
      arguments:
        - CONFIG.alias
  i18n: Hail\I18N\I18N
  event: Hail\Event\EventManager
  acl: Hail\Acl
  browser: Hail\Browser
  cache: Hail\Factory\Cache::simple
  Hail\SimpleCache\CacheInterface: "@cache"
  Psr\SimpleCache\CacheInterface: "@cache"
  cachePool: Hail\Factory\Cache::pool
  Hail\Cache\CacheItemPoolInterface: "@cachePool"
  Psr\Cache\CacheItemPoolInterface: "@cachePool"
  cookie:
    class: Hail\Cookie
    arguments:
      - CONFIG.cookie
  db: Hail\Factory\Database::pdo
  cdb: Hail\Database\Cache
  output: Hail\Output
  router:
    class: Hail\Router
    arguments:
      - CONFIG.route
  session:
    class: Hail\Session
    arguments:
      - CONFIG.session
      - CONFIG.cookie
  storage: Hail\Factory\Storage::mount
  template:
    class: Hail\Latte\Engine
    arguments:
      - CONFIG.template

  # Tools
  arrays: Hail\Util\Arrays
  crypto:
    class: Hail\Util\Crypto
    arguments:
      - CONFIG.crypto.format
  debugger: Hail\Tracy\Debugger
  generators: Hail\Util\Generators
  inflector: Hail\Util\Inflector
  json: Hail\Util\Json
  serialize:
    class: Hail\Util\Serialize
    arguments:
      - CONFIG.env.serialize
  strings: Hail\Util\Strings
  validator: Hail\Util\Validator

  # Application
  app: Hail\Application
  dispatcher:
    class: Hail\Http\Dispatcher
    arguments:
      - CONFIG.middleware
      - "@container"
  lib:
    class: Hail\Util\ObjectFactory
    arguments:
      - App\Library
    classRef: false
  model:
    class: Hail\Util\ObjectFactory
    arguments:
      - App\Model
    classRef: false

  # Middleware
  Hail\Http\Middleware\ScriptPath: "@self"
  Hail\Http\Middleware\Route:
    arguments:
      - "@router"
      - "@container"
